variable check added

diff --git a/mailctl b/mailctl
--- a/mailctl
+++ b/mailctl
@@ -12,6 +12,14 @@ VER=0.11
 
 set -ueo pipefail
 
+if [ -z "$DIR" ] || [ -z "$CONTAINER" ] || [ -z "$TIMEOUT" ]; then
+	echo "Error: Not all setup variables are set."
+	echo
+	echo "You can configure them in '$0'"
+	echo
+	exit 1
+fi >&2
+
 _checkBin() {
 	local cmd
 	for cmd in "$@"; do
